### ISSUE TITLE
关于xuehai与其他app共存的原理

### ISSUE THREAD

**Issue by Hwenray** [HQY-admin/openxuehai#1]
请问是什么方法呢？

**Comment by HQY-admin** [comment]
加我Q说，学海内鬼多，已经查到我了 1339272036

**Comment by HWR20080716** [comment]
抱歉没q，只有钉钉hwenray

**Comment by HWR20080716** [comment]
你有twrp?能给下吗，之前刷了个骗人的p200 twrp，直接砖了，只能10元买刷机包(好贵啊)

**Comment by HQY-admin** [comment]
> 你有twrp?能给下吗，之前刷了个骗人的p200 twrp，直接砖了，只能10元买刷机包(好贵啊)

有，twrp，固件包全都有，你是不是叫huang wen rui

**Comment by HQY-admin** [comment]
> 你有twrp?能给下吗，之前刷了个骗人的p200 twrp，直接砖了，只能10元买刷机包(好贵啊)

钉钉好像手机号可以加，你搜一下15107632175

**Comment by Hwenray** [comment]
> > 你有twrp?能给下吗，之前刷了个骗人的p200 twrp，直接砖了，只能10元买刷机包(好贵啊)
> 
> 钉钉好像手机号可以加，你搜一下15107632175

建议删除

**Comment by HQY-admin** [comment]
> > > 你有twrp?能给下吗，之前刷了个骗人的p200 twrp，直接砖了，只能10元买刷机包(好贵啊)
> > 
> > 钉钉好像手机号可以加，你搜一下1********75
> 
> 建议删除
毕业了谁还搞我😘
